"""
Connect Happy Valley Yodel Events Sync
Pulls local events from the Yodel widget JSON API and upserts to Supabase.

This is a second standalone job (GitHub Actions, hourly) alongside the
GeoDirectory places sync (sync.py). It shares that sync's conventions —
env/secrets, Supabase client, logging, batched upsert, --dry-run — but writes
to the `events` table instead of `places`.

iOS CONTRACT (why transform_event looks the way it does)
--------------------------------------------------------
The iOS `Event` model (ConnectHappyValley/Models/Event.swift) decodes the whole
Tonight result set all-or-nothing and treats several columns as REQUIRED:
  - `title`
  - `venue_name`  (decode(String) — must be NON-EMPTY)
  - `start_time`
  - `category`    (a non-optional EventCategory enum; see config/event_categories.py)
  - `created_at`, `updated_at`
  - `id`          (uuid; generated by the DB default, never set here)
And it only ever returns rows where `is_active = true`.

So every row we write MUST carry a non-empty venue_name, a valid category, a
start_time, and created_at/updated_at, or synced rows will be invisible or —
worse — break the whole Tonight tab decode. transform_event guarantees that.

UPSERT KEY
----------
The `events` table gained `source_id` (unique) + `source` columns via
supabase/migrations/20260707120000_add_events_source_columns.sql, mirroring
places' `place_id`/`source`. We upsert on_conflict="source_id" with the Yodel
event id, so reruns update in place. The uuid `id` stays DB-generated.

STALENESS
---------
The feed is a rolling ~30-day window and upsert never deletes, so without a
reconcile step past/expired events would linger is_active=true. After upsert we:
  1. Always deactivate past events: source='yodel' rows whose
     coalesce(end_time, start_time) < now().
  2. Guarded prune: deactivate source='yodel' rows whose source_id is not in the
     current feed — SKIPPED if this run's feed is < 50% of the prior active
     count, so a partial/failed fetch can't wipe the tab.
--dry-run skips all writes (upsert and both deactivation passes).
"""

import os
import re
import sys
import html
import logging
import argparse
from datetime import datetime, timezone
from typing import Optional

import requests
from supabase import create_client, Client
from dotenv import load_dotenv

from config.event_categories import (
    VALID_EVENT_CATEGORIES,
    event_category_for_names,
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
)
log = logging.getLogger(__name__)

# Load environment
load_dotenv()

# The Yodel feed URL is unauthenticated — the token is baked into the path, so
# it is treated as a secret and MUST be supplied via env / GitHub secret.
YODEL_FEED_URL = os.environ.get("YODEL_FEED_URL")
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

# Constants
REQUEST_TIMEOUT = 30
UPSERT_BATCH_SIZE = 100
# Skip the not-in-feed prune when this run's feed is smaller than this fraction
# of the prior active Yodel row count (partial/failed-fetch guard).
PRUNE_GUARD_FRACTION = 0.5
# Test/junk events: exact subject, and (belt-and-braces) organizer. Organizer
# "Happy Valley" alone is NOT sufficient — legitimate events use it too.
TEST_SUBJECT = "testing the input"
TEST_ORGANIZER = "happy valley"
# venue_name is required non-empty; final fallback when organizer + city are both blank.
VENUE_NAME_FALLBACK = "Happy Valley"


def validate_env(dry_run: bool = False):
    """Ensure required environment variables are set.

    The feed URL is required even for a dry run (a dry run still fetches).
    In dry-run mode we never touch Supabase, so its credentials aren't required.
    """
    if not YODEL_FEED_URL:
        log.error("Missing required environment variable: YODEL_FEED_URL")
        sys.exit(1)
    if dry_run:
        return
    missing = []
    if not SUPABASE_URL:
        missing.append("SUPABASE_URL")
    if not SUPABASE_SERVICE_ROLE_KEY:
        missing.append("SUPABASE_SERVICE_ROLE_KEY")
    if missing:
        log.error(f"Missing required environment variables: {missing}")
        sys.exit(1)


def clean_text(value: Optional[str]) -> str:
    """Decode HTML entities and repair common double-encoded UTF-8 mojibake.

    Mirrors sync.py's clean_text. Used for display strings (title, description,
    venue, tags) — NOT for URLs, which must stay byte-exact.
    """
    if not value:
        return ""
    cleaned = html.unescape(value)
    for codec in ("latin-1", "cp1252"):
        try:
            cleaned = cleaned.encode(codec).decode("utf-8")
            break
        except (UnicodeEncodeError, UnicodeDecodeError):
            continue
    return cleaned.strip()


# Raw http(s):// and www. URLs (with their long tracking query strings) are
# noise no user wants to read AND — being unbreakable — they force the iOS
# layout wider than the screen. Strip them from the DESCRIPTION only. The
# `(?<![\w@])` lookbehind means emails (josh@www.co) and mid-word text are left
# alone; bare typed domains (no scheme, no www.) are also left alone.
_URL_RE = re.compile(r"(?<![\w@])(?:https?://|www\.)\S+", re.IGNORECASE)

# Words a description commonly dangles on once a trailing URL is removed
# (e.g. "Get tickets at <url>" -> "Get tickets at"). Used only to null SHORT
# leftover fragments, never long descriptions.
_DANGLERS = {
    "to", "at", "on", "in", "for", "via", "from", "with", "by", "of", "and",
    "or", "visit", "see", "here", "link", "register", "tickets", "info",
    "details", "more", "get", "go",
}


def strip_urls(text: str) -> Optional[str]:
    """Remove raw URLs from an event description. Returns the cleaned text, or
    None when stripping leaves only a semantically-empty fragment (better to
    show no description than a "Please visit for" stub — same principle as the
    photo-less / fabricated-description decisions).

    DESCRIPTION ONLY — never call this on source_url / image_url.
    """
    if not text:
        return text
    stripped = _URL_RE.sub("", text)
    if stripped == text:
        return text  # no URL present — don't touch (preserves legit short descriptions)
    # Collapse the whitespace the removal left, then trim dangling trailing punctuation.
    s = re.sub(r"[ \t]{2,}", " ", stripped)
    s = re.sub(r"[ \t]*\n[ \t]*", "\n", s).strip()
    s = re.sub(r"[\s:;,\-–—]+$", "", s).strip()
    tail = s.split()[-1].strip(".,;:—-()").lower() if s.split() else ""
    dangling = tail in _DANGLERS
    # Null genuine fragments only: very short, or short-ish and ending on a dangler.
    if len(s) < 20 or (len(s) < 40 and dangling):
        return None
    return s


def fetch_yodel() -> list:
    """Fetch the entire Yodel feed. It's a single un-paginated JSON array."""
    log.info("Fetching Yodel feed (URL configured via YODEL_FEED_URL)")
    response = requests.get(
        YODEL_FEED_URL,
        timeout=REQUEST_TIMEOUT,
        headers={"Accept": "application/json"},
    )
    response.raise_for_status()
    data = response.json()
    if not isinstance(data, list):
        log.error(f"Unexpected Yodel payload type: {type(data).__name__} (expected list)")
        sys.exit(1)
    return data


def is_test_event(event: dict) -> bool:
    """Junk/test events: subject 'Testing the Input' from organizer 'Happy Valley'."""
    subject = (event.get("subject") or "").strip().lower()
    organizer = (event.get("organizer_name") or "").strip().lower()
    return subject == TEST_SUBJECT and organizer == TEST_ORGANIZER


def is_cancelled_event(event: dict) -> bool:
    """Cancelled events: subject prefixed 'CANCELLED' or a 'cancelled' tag."""
    subject = (event.get("subject") or "").strip().upper()
    if subject.startswith("CANCELLED"):
        return True
    for tag in event.get("tags") or []:
        if (tag.get("name") or "").strip().lower() == "cancelled":
            return True
    return False


def dedup_events(events: list) -> list:
    """Collapse duplicate events, keeping the first of each group.

    Primary key: Yodel's `duplicate_id` (events sharing a non-null value are the
    same event surfaced by multiple sources). Fallback for null duplicate_id:
    (subject, start) — a same-title, same-start collision. First occurrence in
    feed order wins.
    """
    seen = set()
    survivors = []
    for event in events:
        dup_id = event.get("duplicate_id")
        if dup_id:
            key = ("dup", str(dup_id))
        else:
            key = (
                "subj",
                (event.get("subject") or "").strip().lower(),
                event.get("start"),
            )
        if key in seen:
            continue
        seen.add(key)
        survivors.append(event)
    return survivors


def _venue_name(event: dict) -> str:
    """Required non-empty venue name: organizer → city → constant fallback."""
    organizer = clean_text(event.get("organizer_name"))
    if organizer:
        return organizer
    location = event.get("location") or {}
    city = clean_text(location.get("city"))
    if city:
        return city
    return VENUE_NAME_FALLBACK


def transform_event(event: dict, now_iso: str) -> Optional[dict]:
    """Map a Yodel event to our Supabase `events` schema.

    Returns None (defensively) when a row would violate the iOS contract —
    missing title or start_time, or an unresolvable category. We NEVER emit a
    row that would break the Tonight decode.
    """
    source_id = event.get("id")
    if not source_id:
        return None

    title = clean_text(event.get("subject"))
    if not title:
        log.warning(f"Event {source_id} has no subject — skipping")
        return None

    start_time = event.get("start")
    if not start_time:
        log.warning(f"Event {source_id} ({title!r}) has no start — skipping")
        return None

    # end_time is null when Yodel flags the end as synthetic/unspecified.
    end_time = None if event.get("endDateMissing") else event.get("end")

    category = event_category_for_names(
        [c.get("name") for c in (event.get("categories") or [])]
    )
    if category not in VALID_EVENT_CATEGORIES:
        # Should be impossible (mapper defaults to 'other'); guard anyway.
        log.warning(f"Event {source_id} ({title!r}) resolved invalid category {category!r} — skipping")
        return None

    location = event.get("location") or {}
    tags = [clean_text(t.get("name")) for t in (event.get("tags") or [])]
    tags = [t for t in tags if t]

    # Real event image (proxied). media_url is the web-sized variant.
    image_url = event.get("media_url") or event.get("raw_media_url") or None

    return {
        # --- upsert key + provenance ---
        "source": "yodel",
        "source_id": str(source_id),

        # --- iOS-required / iOS-read columns ---
        "title": title,
        "venue_name": _venue_name(event),                 # REQUIRED non-empty
        "venue_address": clean_text(location.get("full")) or None,
        "start_time": start_time,                         # REQUIRED
        "end_time": end_time,
        "category": category,                             # REQUIRED valid enum
        "price": None,                                    # no Yodel equivalent → Free
        "tags": tags,
        "image_url": image_url,
        "going_count": 0,                                 # no Yodel equivalent
        "description": strip_urls(clean_text(event.get("description"))) or None,
        # venue_symbol is intentionally NOT written: the column doesn't exist on
        # the events table and the iOS Event decoder ignores it (it derives the
        # symbol from `category`). Writing it fails the upsert (schema cache).
        "source_url": event.get("url") or None,           # byte-exact URL
        "is_active": True,
        "created_at": now_iso,
        "updated_at": now_iso,
    }


def sync_to_supabase(supabase: Client, records: list) -> dict:
    """Upsert records to the Supabase events table on the source_id key."""
    if not records:
        return {"upserted": 0, "errors": 0}

    upserted = 0
    errors = 0
    for i in range(0, len(records), UPSERT_BATCH_SIZE):
        batch = records[i:i + UPSERT_BATCH_SIZE]
        try:
            supabase.table("events").upsert(
                batch,
                on_conflict="source_id",
            ).execute()
            upserted += len(batch)
            log.info(f"Upserted batch of {len(batch)} (total so far: {upserted})")
        except Exception as e:
            log.error(f"Failed to upsert batch: {e}")
            errors += len(batch)
    return {"upserted": upserted, "errors": errors}


def count_active_yodel_rows(supabase: Client) -> int:
    """Count currently-active source='yodel' rows (prior state, pre-prune)."""
    resp = (
        supabase.table("events")
        .select("source_id", count="exact")
        .eq("source", "yodel")
        .eq("is_active", True)
        .execute()
    )
    return resp.count or 0


def deactivate_past_events(supabase: Client, now_iso: str) -> int:
    """Set is_active=false for source='yodel' events already in the past.

    'Past' = coalesce(end_time, start_time) < now. PostgREST can't express
    coalesce in a filter, so we run it as two updates:
      (a) rows with an end_time, where end_time < now
      (b) rows with no end_time, where start_time < now
    """
    total = 0

    # (a) has end_time and it's past
    resp = (
        supabase.table("events")
        .update({"is_active": False, "updated_at": now_iso})
        .eq("source", "yodel")
        .eq("is_active", True)
        .not_.is_("end_time", "null")
        .lt("end_time", now_iso)
        .execute()
    )
    total += len(resp.data or [])

    # (b) no end_time, start_time is past
    resp = (
        supabase.table("events")
        .update({"is_active": False, "updated_at": now_iso})
        .eq("source", "yodel")
        .eq("is_active", True)
        .is_("end_time", "null")
        .lt("start_time", now_iso)
        .execute()
    )
    total += len(resp.data or [])
    return total


def prune_not_in_feed(supabase: Client, current_ids: set, prior_active: int, now_iso: str) -> dict:
    """Deactivate active source='yodel' rows whose source_id isn't in this feed.

    Guarded: if this run's feed is smaller than PRUNE_GUARD_FRACTION of the
    prior active count, we SKIP pruning entirely so a partial/failed fetch can't
    mass-deactivate the Events tab.
    """
    feed_count = len(current_ids)
    if prior_active > 0 and feed_count < PRUNE_GUARD_FRACTION * prior_active:
        log.warning(
            f"PRUNE SKIPPED: feed has {feed_count} events but {prior_active} were "
            f"active (< {int(PRUNE_GUARD_FRACTION * 100)}%) — refusing to prune "
            f"(likely a partial/failed fetch)."
        )
        return {"pruned": 0, "skipped": True}

    # Fetch active source_ids still in the table, diff against the current feed.
    resp = (
        supabase.table("events")
        .select("source_id")
        .eq("source", "yodel")
        .eq("is_active", True)
        .execute()
    )
    active_ids = {r["source_id"] for r in (resp.data or []) if r.get("source_id")}
    stale = list(active_ids - current_ids)
    if not stale:
        return {"pruned": 0, "skipped": False}

    pruned = 0
    for i in range(0, len(stale), UPSERT_BATCH_SIZE):
        batch = stale[i:i + UPSERT_BATCH_SIZE]
        resp = (
            supabase.table("events")
            .update({"is_active": False, "updated_at": now_iso})
            .eq("source", "yodel")
            .in_("source_id", batch)
            .execute()
        )
        pruned += len(resp.data or [])
    return {"pruned": pruned, "skipped": False}


def main(dry_run: bool = False):
    log.info("=" * 60)
    log.info("Connect Happy Valley Yodel Events Sync")
    if dry_run:
        log.info("*** DRY RUN — no writes to Supabase ***")
    log.info(f"Started at {datetime.now(timezone.utc).isoformat()}")
    log.info(f"Running commit: {os.environ.get('GITHUB_SHA') or 'unknown (not running in GitHub Actions)'}")
    log.info("Feed URL: configured via YODEL_FEED_URL")
    log.info("=" * 60)

    validate_env(dry_run=dry_run)
    supabase = None if dry_run else create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

    now_iso = datetime.now(timezone.utc).isoformat()

    # Fetch
    all_events = fetch_yodel()
    log.info(f"Total fetched: {len(all_events)} events")

    # Filter: test/junk
    non_test = [e for e in all_events if not is_test_event(e)]
    test_excluded = len(all_events) - len(non_test)

    # Filter: cancelled
    non_cancelled = [e for e in non_test if not is_cancelled_event(e)]
    cancelled_excluded = len(non_test) - len(non_cancelled)

    # Dedup
    deduped = dedup_events(non_cancelled)
    dupes_collapsed = len(non_cancelled) - len(deduped)

    # Transform (drop any that would violate the iOS contract)
    records = []
    transform_skipped = 0
    for e in deduped:
        rec = transform_event(e, now_iso)
        if rec is None:
            transform_skipped += 1
            continue
        records.append(rec)

    # Consolidated pipeline summary (the numbers to eyeball on a dry run).
    log.info("-" * 60)
    log.info("Pipeline summary:")
    log.info(f"  Fetched:            {len(all_events)}")
    log.info(f"  Test excluded:      {test_excluded}")
    log.info(f"  Cancelled excluded: {cancelled_excluded}")
    log.info(f"  Dupes collapsed:    {dupes_collapsed}")
    if transform_skipped:
        log.info(f"  Transform skipped:  {transform_skipped}")
    log.info(f"  Final records:      {len(records)}")
    log.info("-" * 60)

    if dry_run:
        log.info(f"DRY RUN — would upsert {len(records)} events; staleness passes skipped (no DB writes)")
        log.info("=" * 60)
        log.info("Dry run finished")
        log.info("=" * 60)
        return

    # Capture prior active count BEFORE writing, for the prune guard.
    prior_active = count_active_yodel_rows(supabase)
    log.info(f"Prior active Yodel rows: {prior_active}")

    # Upsert
    result = sync_to_supabase(supabase, records)
    log.info(f"Upsert complete: {result['upserted']} upserted, {result['errors']} errors")

    # Staleness 1: always deactivate past events.
    past = deactivate_past_events(supabase, now_iso)
    log.info(f"Deactivated {past} past event(s) (coalesce(end,start) < now)")

    # Staleness 2: guarded prune of rows no longer in the feed.
    current_ids = {r["source_id"] for r in records}
    prune = prune_not_in_feed(supabase, current_ids, prior_active, now_iso)
    if prune["skipped"]:
        log.info("Prune of not-in-feed rows was SKIPPED by the fetch-size guard")
    else:
        log.info(f"Deactivated {prune['pruned']} event(s) no longer in the feed")

    log.info("=" * 60)
    log.info("Sync finished")
    log.info("=" * 60)

    if result["errors"] > 0:
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connect Happy Valley Yodel -> Supabase events sync")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Fetch, filter, and dedup, logging per-stage counts, but SKIP all Supabase writes.",
    )
    args = parser.parse_args()
    main(dry_run=args.dry_run)
