"""
Connect Happy Valley GeoDirectory Sync
Pulls business listings from WordPress GeoDirectory REST API and upserts to Supabase.

This is a standalone job (GitHub Actions, hourly) and is deliberately decoupled
from the iOS app: it only writes to the Supabase `places` table; the iOS app
reads from that table unchanged.

iOS CONTRACT (why transform_listing looks the way it does)
----------------------------------------------------------
The iOS `Place` model (ConnectHappyValley/Models/Place.swift) decodes the whole
Discover result set all-or-nothing and treats several columns as REQUIRED /
non-optional:
  - `type`       -> a PlaceType enum (restaurant|bar|cafe|hotel|experience|venue|shop)
  - `name`
  - `created_at`, `updated_at`
  - `id`         (uuid; generated by the DB default, never set here)
And it only ever returns rows where `is_active = true`.

So every row we write MUST carry a valid `type`, `is_active = true`, and
`created_at`/`updated_at`, or synced rows will either be invisible or — worse —
break decoding for the entire Discover tab (including the curated rows). The
transform below guarantees all of that. Listings whose category has no iOS type
mapping are SKIPPED and logged, never written with a null type.

The app reads `image_url` and `is_featured`; GeoDirectory's native names are
`photo_url`/`featured`. We populate BOTH conventions so the data is correct for
the app today and self-describing in the table.
"""

import os
import sys
import html
import logging
import time
import argparse
import unicodedata
from datetime import datetime, timezone
from typing import Optional

import requests
from supabase import create_client, Client
from dotenv import load_dotenv

from config.categories import (
    ALLOWED_PARENT_IDS,
    PARENT_BUCKET_NAMES,
    PARENT_ID_TO_PLACE_TYPE,
    VALID_PLACE_TYPES,
    place_type_for_category_name,
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
)
log = logging.getLogger(__name__)

# Load environment
load_dotenv()

# Base URL of the GeoDirectory source site. Overridable via env/secret (e.g.
# to point at a pre-launch staging host with GEODIR_BASIC_AUTH set).
GEODIR_BASE_URL = os.environ.get("GEODIR_BASE_URL", "https://connecthappyvalley.com")
GEODIR_BASIC_AUTH = os.environ.get("GEODIR_BASIC_AUTH")  # Format: "user:pass" or None when launched
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

# Constants
PER_PAGE = 100
MAX_PAGES = 50  # Safety: max 5000 listings
REQUEST_TIMEOUT = 30
RATE_LIMIT_SLEEP = 0.5  # 500ms between page requests

# Trailing slash on the base URL would produce a double slash in the request
# path; normalize once here so the secret can be set either way.
GEODIR_BASE_URL = GEODIR_BASE_URL.rstrip("/")


def validate_env(dry_run: bool = False):
    """Ensure required environment variables are set.

    In dry-run mode we never touch Supabase, so its credentials aren't required
    — a dry run only needs GeoDirectory access.
    """
    if dry_run:
        return
    missing = []
    if not SUPABASE_URL:
        missing.append("SUPABASE_URL")
    if not SUPABASE_SERVICE_ROLE_KEY:
        missing.append("SUPABASE_SERVICE_ROLE_KEY")
    if missing:
        log.error(f"Missing required environment variables: {missing}")
        sys.exit(1)


def validate_category_config():
    """Surface (without crashing) any gaps in the bucket config.

    Every allowed bucket needs a default PlaceType and a display name, or
    matching listings get skipped / log as "Unknown". Logging this at startup
    keeps the structures in config/categories.py honest.
    """
    missing_type = ALLOWED_PARENT_IDS - set(PARENT_ID_TO_PLACE_TYPE)
    if missing_type:
        log.warning(
            f"{len(missing_type)} allowed buckets have NO default PlaceType — "
            f"their listings will be SKIPPED: {sorted(missing_type)}"
        )
    bad_type = {b: t for b, t in PARENT_ID_TO_PLACE_TYPE.items() if t not in VALID_PLACE_TYPES}
    if bad_type:
        log.warning(f"Bucket defaults with invalid PlaceType values: {bad_type}")
    missing_name = ALLOWED_PARENT_IDS - set(PARENT_BUCKET_NAMES)
    if missing_name:
        log.warning(f"Allowed buckets with no display name: {sorted(missing_name)}")


def get_auth_header() -> Optional[tuple]:
    """Return auth tuple for requests, or None if no auth configured."""
    if not GEODIR_BASIC_AUTH:
        return None
    if ":" not in GEODIR_BASIC_AUTH:
        log.error("GEODIR_BASIC_AUTH must be in format 'username:password'")
        sys.exit(1)
    user, pw = GEODIR_BASIC_AUTH.split(":", 1)
    return (user, pw)


def fetch_listings_page(page: int, auth: Optional[tuple]) -> list:
    """Fetch a single page of GeoDirectory listings."""
    url = f"{GEODIR_BASE_URL}/wp-json/geodir/v2/places"
    params = {"per_page": PER_PAGE, "page": page}
    log.info(f"Fetching page {page} from {url}")

    response = requests.get(
        url,
        params=params,
        auth=auth,
        timeout=REQUEST_TIMEOUT,
        headers={"Accept": "application/json"},
    )

    if response.status_code == 400:
        # WordPress returns 400 when page exceeds available pages
        log.info(f"Page {page} returned 400 — likely end of results")
        return []

    response.raise_for_status()
    return response.json()


def fetch_all_categories(auth: Optional[tuple]) -> dict:
    """Fetch all categories once and return an {id: parent} map.

    Listings embed subcategory ids but not reliably their parent, so we resolve
    parent via this map. It's static during a run, so we fetch it once up front.
    """
    cat_url = f"{GEODIR_BASE_URL}/wp-json/geodir/v2/places/categories"
    id_to_parent = {}
    for page in range(1, 20):  # ~700 categories max at 100/page
        response = requests.get(
            cat_url,
            params={"per_page": 100, "page": page},
            auth=auth,
            timeout=REQUEST_TIMEOUT,
            headers={"Accept": "application/json"},
        )
        if response.status_code == 400:
            break
        response.raise_for_status()
        cats = response.json()
        if not cats:
            break
        for cat in cats:
            try:
                id_to_parent[int(cat["id"])] = int(cat["parent"])
            except (KeyError, TypeError, ValueError):
                continue
    log.info(f"Loaded {len(id_to_parent)} categories with parent mappings")
    return id_to_parent


def bucket_id_for_category(cat: dict, id_to_parent: dict) -> Optional[int]:
    """Resolve the allowed top-level bucket id for a single category, or None.

    Handles both shapes: a listing tagged directly with a top-level bucket
    (rare), and the common case of a subcategory whose parent is a bucket.
    """
    cat_id = cat.get("id")
    if cat_id is None:
        return None
    try:
        cat_id = int(cat_id)
    except (TypeError, ValueError):
        return None
    # The category IS itself a whitelisted top-level bucket.
    if cat_id in ALLOWED_PARENT_IDS:
        return cat_id
    # ...or its parent is a whitelisted bucket.
    parent_id = id_to_parent.get(cat_id)
    if parent_id in ALLOWED_PARENT_IDS:
        return parent_id
    return None


def included_category(listing: dict, id_to_parent: dict) -> Optional[tuple]:
    """Return (category dict, bucket_id) for the listing's first allowed category.

    A listing can carry several categories; we use the first one — in API order —
    that resolves to an allowed bucket, and base both the include decision and
    the type/category fields on it, so filtering and typing never disagree.
    """
    for cat in listing.get("post_category", []) or []:
        bucket_id = bucket_id_for_category(cat, id_to_parent)
        if bucket_id is not None:
            return cat, bucket_id
    return None


def should_include_listing(listing: dict, id_to_parent: dict) -> bool:
    """Whitelist check — does this listing belong to an allowed top-level bucket?"""
    return included_category(listing, id_to_parent) is not None


def resolve_place_type(cat_name: Optional[str], bucket_id: int) -> Optional[str]:
    """Two-tier type resolution: name refinement over the guaranteed bucket default.

    Returns a valid iOS PlaceType, or None only if the bucket has no default
    (a config error caught by validate_category_config()).
    """
    refined = place_type_for_category_name(cat_name)
    if refined in VALID_PLACE_TYPES:
        return refined
    return PARENT_ID_TO_PLACE_TYPE.get(bucket_id)


def clean_text(value: Optional[str]) -> str:
    """Decode HTML entities and repair common mojibake.

    Used for display strings (names, descriptions, address parts, category
    names) — NOT for URLs or contact fields, which must stay byte-exact.
    """
    if not value:
        return ""

    # Step 1: HTML-unescape (handles &#038; &amp; &#8217; &#8211; etc.)
    cleaned = html.unescape(value)

    # Step 2: Repair double-encoded UTF-8 mojibake. When valid UTF-8 was decoded
    # as a single-byte codec and re-encoded as UTF-8 (a classic WordPress bug),
    # round-tripping <codec> -> utf-8 undoes it. We try latin-1 first ("KafÃ©" ->
    # "Kafé") then cp1252, which is needed for the curly-quote/dash family
    # ("â€™" -> "'", "â€“" -> "–") whose bytes fall in 0x80-0x9F and aren't in
    # latin-1. Each attempt is guarded; a string that's already clean raises and
    # is kept as-is.
    for codec in ("latin-1", "cp1252"):
        try:
            cleaned = cleaned.encode(codec).decode("utf-8")
            break
        except (UnicodeEncodeError, UnicodeDecodeError):
            continue

    return cleaned.strip()


def _is_mshots_url(url: str) -> bool:
    """True for WordPress mshots auto-screenshots (s.wordpress.com/mshots/...).

    These are placeholder screenshots of a business's website, not real photos,
    so we treat them as "no photo" rather than write them into image_url/photo_url.
    """
    return "s.wordpress.com/mshots" in url.lower()


def extract_photo_url(listing: dict) -> Optional[str]:
    """Pull the best available real photo URL from a GeoDirectory listing.

    Priority: featured_image.src > images[0].src > None. We do NOT gate on `id`
    (mshots screenshots always carry id=0). We DO skip s.wordpress.com/mshots
    screenshots: a real images[0] can win over an mshots featured_image, and if
    mshots is the only candidate the photo is left null.
    """
    candidates = []

    featured = listing.get("featured_image")
    if isinstance(featured, dict):
        src = featured.get("src")
        if src and isinstance(src, str) and src.strip():
            candidates.append(src.strip())

    images = listing.get("images")
    if isinstance(images, list) and images:
        first = images[0]
        if isinstance(first, dict):
            src = first.get("src")
            if src and isinstance(src, str) and src.strip():
                candidates.append(src.strip())

    for src in candidates:
        if not _is_mshots_url(src):
            return src

    return None


# ---------------------------------------------------------------------------
# Post-transform exclusion filters. These run on the CLEANED record (name,
# category_name, description already HTML-unescaped + mojibake-repaired by
# clean_text), which is why they live after transform_listing rather than
# alongside the raw-listing whitelist.
# ---------------------------------------------------------------------------

# Confirmed adult venues, matched by exact (normalized) name. Venue names are
# REDACTED in this public copy. The category/phrase checks below independently
# catch all of them too — each carries category_name "Adult Entertainment" —
# so this is a belt-and-braces anchor, deliberately narrow (exact equality,
# not substring) so ordinary businesses that happen to share a word with a
# venue name are never caught.
ADULT_EXACT_NAMES = {
    "redacted-venue-1",
    "redacted-venue-2",
    "redacted-venue-3",
    "redacted-venue-4",
}

# Whole-phrase signals. "adult entertainment" is the GeoDirectory subcategory
# these venues sit under; the two club phrases are unambiguous. No loose single
# words (exotic/topless/adult-alone) — they risk false positives and caught
# nothing in the live data.
ADULT_PHRASES = (
    "adult entertainment",
    "gentlemen's club",
    "strip club",
)


def _normalize_for_match(text: Optional[str]) -> str:
    """Casefold, strip, and straighten curly apostrophes for tolerant matching."""
    if not text:
        return ""
    return text.replace("’", "'").replace("‘", "'").casefold().strip()


def is_adult_listing(record: dict) -> bool:
    """True if a transformed record is an adult-entertainment venue (excluded).

    Precision-biased: exact-name match on the confirmed venues, plus whole
    phrases in name/category/description. See ADULT_EXACT_NAMES / ADULT_PHRASES.
    """
    if _normalize_for_match(record.get("name")) in ADULT_EXACT_NAMES:
        return True
    blob = " ".join(
        _normalize_for_match(record.get(field))
        for field in ("name", "category_name", "description")
    )
    return any(phrase in blob for phrase in ADULT_PHRASES)


def is_unrecoverable_name(name: Optional[str]) -> bool:
    """True if a name is encoding garbage that clean_text couldn't repair.

    Conservative — flags only names that are genuinely unusable:
      - empty/whitespace after cleaning,
      - contain the Unicode replacement char (U+FFFD),
      - contain a C0/C1 control char (the residue of a failed cp1252 round-trip
        on double-encoded CJK — the signature of the mojibake we can't fix), or
      - contain no ASCII letter at all (pure non-Latin garbage).
    Legitimate accented / Vietnamese / Latin+CJK names all keep at least one
    ASCII letter and carry no control chars, so they survive.
    """
    if not name:
        return True
    s = name.strip()
    if not s:
        return True
    if "�" in s:
        return True
    for ch in s:
        if unicodedata.category(ch) == "Cc" and ch not in "\t\n\r":
            return True
    if not any(("a" <= c <= "z") or ("A" <= c <= "Z") for c in s):
        return True
    return False


# Source-side test/placeholder listings the CHV team left in GeoDirectory — the
# "(don't delete) The Flying Pig Sty" rows (a WordPress demo listing whose copy
# is a duplicate of Allen Street Grill) and any "do not delete" markers. Never
# visitor-facing. Matched on normalized-name substrings (_normalize_for_match
# casefolds and straightens curly apostrophes, so both "don't" forms match).
JUNK_NAME_SUBSTRINGS = (
    "flying pig sty",
    "don't delete",
    "do not delete",
    "dont delete",
)


def is_junk_listing(record: dict) -> bool:
    """True if a record is a source-side test/placeholder listing (excluded)."""
    name = _normalize_for_match(record.get("name"))
    return any(sub in name for sub in JUNK_NAME_SUBSTRINGS)


def transform_listing(listing: dict, id_to_parent: dict) -> Optional[dict]:
    """Map a GeoDirectory listing to our Supabase `places` schema.

    Returns None when the listing belongs to no allowed bucket (filter already
    excluded those) or — defensively — when its bucket has no default type. We
    NEVER emit a row with a null `type`, because that would break the iOS
    Discover decode for every row.
    """
    inc = included_category(listing, id_to_parent)
    if inc is None:
        return None
    cat, bucket_id = inc

    place_type = resolve_place_type(cat.get("name"), bucket_id)
    if place_type not in VALID_PLACE_TYPES:
        # Defensive: bucket has no valid default (config error). Skip, don't emit null.
        log.warning(
            f"Listing {listing.get('id')} in bucket {bucket_id} "
            f"({PARENT_BUCKET_NAMES.get(bucket_id, '?')}) yielded invalid type "
            f"'{place_type}' — skipping"
        )
        return None

    # Title — prefer raw (canonical WordPress field) over rendered (entity-encoded HTML).
    title_obj = listing.get("title", {}) or {}
    name = clean_text(title_obj.get("raw") or title_obj.get("rendered") or "Unknown")

    # Description — prefer raw over rendered, then clean.
    content_obj = listing.get("content", {}) or {}
    description = clean_text(content_obj.get("raw") or content_obj.get("rendered") or "")

    # Featured image (src-first, no id gate, mshots screenshots kept).
    photo_url = extract_photo_url(listing)

    # Lat/lng — handle strings
    lat = listing.get("latitude")
    lng = listing.get("longitude")
    try:
        lat = float(lat) if lat else None
        lng = float(lng) if lng else None
    except (ValueError, TypeError):
        lat = None
        lng = None

    # Penn State fields
    student_discount_obj = listing.get("student_discount", {})
    student_discount = (
        student_discount_obj.get("raw") == "1"
        if isinstance(student_discount_obj, dict) else False
    )
    distance_to_campus = listing.get("distance_to_campus") or None

    featured = bool(listing.get("featured"))

    # Stamp created_at/updated_at explicitly. The iOS model decodes both as
    # non-optional Dates, and the fetch is all-or-nothing, so a missing value on
    # even one row would blank the Discover tab. We set both to "now" rather than
    # rely on (unverified) DB column defaults; true provenance is carried by
    # `place_id` + `last_synced`, so created_at tracking sync time is acceptable
    # for auto-synced directory rows.
    now_iso = datetime.now(timezone.utc).isoformat()

    return {
        # --- GeoDirectory upsert key ---
        "place_id": listing.get("place_id") or f"gd_{listing.get('id')}",

        # --- iOS-required / iOS-read columns ---
        "name": name,
        "type": place_type,                  # REQUIRED by iOS PlaceType enum
        "description": description or None,
        "is_active": True,                   # RLS gate — app only returns is_active=true
        "needs_local_review": True,          # auto-synced; flag for human curation
        "image_url": photo_url,              # iOS reads image_url ...
        "is_featured": featured,             # ... and is_featured
        "latitude": lat,
        "longitude": lng,
        "created_at": now_iso,
        "updated_at": now_iso,

        # --- GeoDirectory-native columns (added by the migration) ---
        "phone": listing.get("phone") or None,
        "email": listing.get("email") or None,
        "website": listing.get("website") or None,
        "slug": listing.get("slug") or None,
        "street": clean_text(listing.get("street")) or None,
        "city": clean_text(listing.get("city")) or None,
        "region": clean_text(listing.get("region")) or None,
        "zip": listing.get("zip") or None,            # postal code — leave byte-exact
        "country": clean_text(listing.get("country")) or None,
        "featured": featured,                # mirror of is_featured (native name)
        "photo_url": photo_url,              # mirror of image_url (native name)
        "student_discount": student_discount,
        "distance_to_campus": distance_to_campus,
        "facebook_url": listing.get("facebook") or None,
        "instagram_url": listing.get("instagram") or None,
        "category_id": cat.get("id"),
        "category_name": clean_text(cat.get("name")) or None,
        "category_slug": cat.get("slug"),

        # --- sync metadata ---
        "source": "geodirectory",
        "last_synced": now_iso,
    }


# ~50m in latitude/longitude degrees at central-PA latitudes (~0.0005 deg).
DEDUP_COORD_TOL = 0.0005


def dedup_records(records: list) -> list:
    """Collapse near-duplicate listings: same name at near-identical coordinates.

    Two records collapse when they share a normalized name AND their latitude
    and longitude are EACH within DEDUP_COORD_TOL (~50m). We cluster pairwise
    WITHIN each name group (transitive union), not by a rounded grid: a grid
    whose cell equals the tolerance misses pairs that straddle a cell boundary
    (verified to miss ~half the real pairs on live data). O(n^2) within a single
    name is negligible here.

    This can NOT merge genuinely separate locations of a chain — two Sheetz more
    than ~50m apart fall in different clusters and BOTH survive. Records missing
    coordinates can't be proximity-matched, so they fall back to the legacy
    (name, city, street) key.

    Within a collapsed cluster we keep the record with the LONGER (fuller)
    description; ties break on photo presence, then lowest place_id (stable
    across runs) — matching the curated CSV.
    """
    def name_key(rec: dict) -> str:
        return (rec.get("name") or "").strip().casefold()

    def coords(rec: dict):
        lat, lon = rec.get("latitude"), rec.get("longitude")
        if lat is None or lon is None:
            return None
        try:
            return float(lat), float(lon)
        except (TypeError, ValueError):
            return None

    def is_better(new: dict, old: dict) -> bool:
        new_desc = len((new.get("description") or "").strip())
        old_desc = len((old.get("description") or "").strip())
        if new_desc != old_desc:
            return new_desc > old_desc  # fuller description wins
        new_photo = bool((new.get("photo_url") or "").strip())
        old_photo = bool((old.get("photo_url") or "").strip())
        if new_photo != old_photo:
            return new_photo  # then a row with a photo beats one without
        # final tie-break -> lowest place_id (stable across runs)
        return (new.get("place_id") or "") < (old.get("place_id") or "")

    # Split into coordinate-bearing records (proximity dedup) and the rest
    # (legacy (name, city, street) dedup).
    by_name = {}
    no_coord_best = {}
    for rec in records:
        c = coords(rec)
        if c is None:
            city = (rec.get("city") or "").strip().casefold()
            street = (rec.get("street") or "").strip().casefold()
            # Only merge coordinate-less rows when BOTH city and street are
            # present — a shared (name, city, street) is a genuine duplicate.
            # If either is missing, key on the unique place_id so distinct
            # addressless rows that merely share a name are NEVER collapsed.
            # The old fallback keyed on (name, "", "") for such rows, silently
            # dropping unrelated places that happened to share a name.
            if city and street:
                k = (name_key(rec), city, street)
            else:
                k = ("__place_id__", rec.get("place_id") or id(rec))
            existing = no_coord_best.get(k)
            if existing is None or is_better(rec, existing):
                no_coord_best[k] = rec
            continue
        lat, lon = c
        by_name.setdefault(name_key(rec), []).append((rec, lat, lon))

    # Pairwise-cluster within each name group via union-find, then keep the best
    # record per cluster.
    survivors = []
    for group in by_name.values():
        n = len(group)
        parent = list(range(n))

        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        for i in range(n):
            _, la_i, lo_i = group[i]
            for j in range(i + 1, n):
                _, la_j, lo_j = group[j]
                if abs(la_i - la_j) <= DEDUP_COORD_TOL and abs(lo_i - lo_j) <= DEDUP_COORD_TOL:
                    parent[find(i)] = find(j)

        clusters = {}
        for idx in range(n):
            clusters.setdefault(find(idx), []).append(group[idx][0])
        for members in clusters.values():
            best = members[0]
            for rec in members[1:]:
                if is_better(rec, best):
                    best = rec
            survivors.append(best)

    return survivors + list(no_coord_best.values())


def sync_to_supabase(supabase: Client, records: list) -> dict:
    """Upsert records to Supabase places table."""
    if not records:
        return {"inserted": 0, "errors": 0}

    inserted = 0
    errors = 0

    # Upsert in batches of 100
    for i in range(0, len(records), 100):
        batch = records[i:i + 100]
        try:
            supabase.table("places").upsert(
                batch,
                on_conflict="place_id"
            ).execute()
            inserted += len(batch)
            log.info(f"Upserted batch of {len(batch)} (total so far: {inserted})")
        except Exception as e:
            log.error(f"Failed to upsert batch: {e}")
            errors += len(batch)

    return {"inserted": inserted, "errors": errors}


def main(dry_run: bool = False):
    log.info("=" * 60)
    log.info("Connect Happy Valley GeoDirectory Sync")
    if dry_run:
        log.info("*** DRY RUN — no writes to Supabase ***")
    log.info(f"Started at {datetime.now(timezone.utc).isoformat()}")
    # Attribute every run to a code version. GitHub Actions sets GITHUB_SHA;
    # outside CI it's unset, so a local run says so plainly.
    log.info(f"Running commit: {os.environ.get('GITHUB_SHA') or 'unknown (not running in GitHub Actions)'}")
    log.info(f"Base URL: {GEODIR_BASE_URL}")
    log.info(f"Allowed buckets: {len(ALLOWED_PARENT_IDS)} configured")
    log.info("=" * 60)

    validate_env(dry_run=dry_run)
    validate_category_config()
    auth = get_auth_header()
    if auth:
        log.info("HTTP Basic Auth configured (staging mode)")
    else:
        log.info("No HTTP Basic Auth (production mode)")

    # In dry-run mode we never construct a Supabase client — a dry run confirms
    # the filter/dedup counts without needing (or touching) the database.
    supabase = None if dry_run else create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

    # Pre-fetch the category tree once so we can resolve each listing's parent
    # bucket. Without this map, subcategory-tagged listings can't be filtered.
    id_to_parent = fetch_all_categories(auth)
    if not id_to_parent:
        log.error("No categories loaded — cannot resolve parent buckets. Aborting.")
        sys.exit(1)

    # Fetch all pages
    all_listings = []
    for page in range(1, MAX_PAGES + 1):
        listings = fetch_listings_page(page, auth)
        if not listings:
            log.info(f"No more results at page {page} — stopping pagination")
            break
        all_listings.extend(listings)
        log.info(f"Page {page}: {len(listings)} listings (running total: {len(all_listings)})")
        time.sleep(RATE_LIMIT_SLEEP)

    log.info(f"Total fetched: {len(all_listings)} listings")

    # Filter by whitelist (parent-bucket based)
    filtered = [l for l in all_listings if should_include_listing(l, id_to_parent)]
    log.info(f"After whitelist filter: {len(filtered)} listings ({len(all_listings) - len(filtered)} excluded)")

    # Log breakdown by top-level parent bucket for visibility.
    bucket_counts = {}
    for listing in filtered:
        inc = included_category(listing, id_to_parent)
        bucket_id = inc[1] if inc else None
        bucket_counts[bucket_id] = bucket_counts.get(bucket_id, 0) + 1
    log.info("Parent bucket breakdown:")
    for bucket_id, count in sorted(bucket_counts.items(), key=lambda x: -x[1]):
        name = PARENT_BUCKET_NAMES.get(bucket_id, f"Unknown ({bucket_id})")
        log.info(f"  {name}: {count}")

    # Transform (drop any that fail to map — defensive; filter already excluded them)
    records = []
    skipped = 0
    for l in filtered:
        rec = transform_listing(l, id_to_parent)
        if rec is None:
            skipped += 1
            continue
        records.append(rec)
    log.info(f"Transformed {len(records)} records ({skipped} skipped during transform)")

    # Exclusion filters on the cleaned records (run before dedup):
    #   1. adult-entertainment venues, 2. unrecoverable mojibake names,
    #   3. source-side test/placeholder junk (the "Flying Pig Sty" rows).
    before_excl = len(records)
    records = [r for r in records if not is_adult_listing(r)]
    adult_dropped = before_excl - len(records)
    before_moji = len(records)
    records = [r for r in records if not is_unrecoverable_name(r.get("name"))]
    moji_dropped = before_moji - len(records)
    before_junk = len(records)
    records = [r for r in records if not is_junk_listing(r)]
    junk_dropped = before_junk - len(records)
    log.info(
        f"Excluded {adult_dropped} adult-entertainment, "
        f"{moji_dropped} unrecoverable-name, and {junk_dropped} junk listings"
    )

    # Deduplicate near-duplicate listings (same name, coords within ~50m) before upsert.
    before = len(records)
    records = dedup_records(records)
    dropped = before - len(records)
    log.info(f"Dedup: collapsed {before} listings into {len(records)} unique ({dropped} dropped)")

    # Content-integrity: the GeoDirectory `content` field is auto-generated
    # templated placeholder text (per-place but formulaic, and occasionally
    # factually wrong — e.g. a soup shop described as selling furniture), not
    # real business copy. We do NOT surface it. Null every synced description so
    # the app shows only verifiable fields (name, category, location). The value
    # is intentionally kept through the filters and dedup above — where it feeds
    # adult-phrase matching and the "fuller row wins" tie-break — then blanked
    # here, immediately before upsert. Real per-place descriptions are a future
    # curation / grounded-generation pass (tracked separately; do not re-enable
    # by copying `content` back in).
    for r in records:
        r["description"] = None

    # Consolidated pipeline summary (the numbers to eyeball on a dry run).
    log.info("-" * 60)
    log.info("Pipeline summary:")
    log.info(f"  Fetched:                {len(all_listings)}")
    log.info(f"  After whitelist:        {len(filtered)}")
    log.info(f"  After transform:        {before_excl} ({skipped} skipped)")
    log.info(f"  Adult excluded:         {adult_dropped}")
    log.info(f"  Mojibake-name excluded: {moji_dropped}")
    log.info(f"  Junk excluded:          {junk_dropped}")
    log.info(f"  Duplicates collapsed:   {dropped}")
    log.info(f"  Descriptions nulled:    {len(records)} (content-integrity)")
    log.info(f"  Final records:          {len(records)}")
    log.info("-" * 60)

    if dry_run:
        log.info(f"DRY RUN — skipping upsert of {len(records)} records (no database writes)")
        log.info("=" * 60)
        log.info("Dry run finished")
        log.info("=" * 60)
        return

    # Sync
    result = sync_to_supabase(supabase, records)
    log.info(f"Sync complete: {result['inserted']} inserted/updated, {result['errors']} errors")

    log.info("=" * 60)
    log.info("Sync finished")
    log.info("=" * 60)

    # Non-zero exit on batch errors so the GitHub Actions run is visibly red.
    if result["errors"] > 0:
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connect Happy Valley GeoDirectory -> Supabase sync")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Fetch, filter, and dedup, logging per-filter counts, but SKIP the Supabase upsert.",
    )
    args = parser.parse_args()
    main(dry_run=args.dry_run)
